apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.fullname }}-service
  labels:
    app: {{ .Values.app.name  }}
    chart: {{ .Values.app.chart  }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.expose.port }}
    protocol: {{ .Values.expose.protocol }}
    targetPort: 8080
  selector:
    app: {{ .Values.app.name  }}
    chart: {{ .Values.app.chart  }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}

