# Default values for golang-gin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicacount: 1

image:
  repository: asia.gcr.io/gcp-akash-287109/react-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "ee5cb94-develop"

imagepullsecret: registrypullsecret
nameOverride: ""
fullnameOverride: ""


app:
 fullname: react-app-go
 name: react
 chart: chart-go

url:
  endpoint1: http://104.196.53.80:8080
  endpoint2: http://104.196.28.2:8080


expose:
  port: 8080
  protocol: TCP
