apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.fullname }}-config
  labels:
    app: {{ .Values.app.name  }}
    chart: {{ .Values.app.chart  }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.toml: |
    [MySQLConnector]
    mySQLUrl            = "{{ .Values.mysql.url }}"
    mySQLDatabase       = "{{ .Values.mysql.database }}"
    mySQLUsername       = "{{ .Values.mysql.username }}"
    mySQLPassword       = "{{ .Values.mysql.password }}"
    mySQLNetwork        = "{{ .Values.mysql.network }}"

    [RedisConfig]
    address          = "{{ .Values.redis.address }}"

