apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.fullname }}-reactconfig
  labels:
    app: {{ .Values.app.name  }}
    chart: {{ .Values.app.chart  }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
data:
  config.js: |
          var Configs = { APP_URL : "{{ .Values.url.endpoint1 }}",APP_LIKE_URL: "{{ .Values.url.endpoint2 }}",prop2 : "123"}

